version: '3'

services:
  nats-serve:
    image: nats:latest

  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: auth-ms-prod
    ports:
      - ${AUTH_PORT}:${AUTH_PORT}
    environment:
      - NATS_SERVERS=${NATS_SERVERS}
      - PORT=${AUTH_PORT}
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET_AUTH}

  client-gateway:
    build:
      context: ./client-gateway-ms
      dockerfile: dockerfile.prod
    image: client-gateway-ms-prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - NATS_SERVERS=${NATS_SERVERS}
      - PORT=${CLIENT_GATEWAY_PORT}

  product-ms:
    build:
      context: ./product-ms
      dockerfile: dockerfile.prod
    image: product-ms-prod
    environment:
      - NATS_SERVERS=${NATS_SERVERS}
      - PORT=3000
      - DATABASE_URL=file:./dev.db

  payment-ms:
    build:
      context: ./payment-ms
      dockerfile: dockerfile.prod
    image: payment-ms-prod
    ports:
      - ${PAYMENT_PORT}:${PAYMENT_PORT}

    environment:
      - PORT=${PAYMENT_PORT}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - NATS_SERVERS=${NATS_SERVERS}

  orders-ms:
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: orders-ms-prod
    environment:
      - PORT=3007
      - DATABASE_URL=${ORDERS_DATABASE_URL}
      - NATS_SERVERS=${NATS_SERVERS}



